// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251022131822_UpdateDataContext")]
    partial class UpdateDataContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Infrastructure.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Thursday Blend — Brazil Cascavel × Ethiopia Guji A modern twist on a centuries - old ritual.Thursday Blend brings together the depth and balance of Brazil Cascavel with the vibrant aromatics of Ethiopia Guji,creating a uniquely expressive Turkish coffee experience. Smooth and round with a touch of brightness,it captures the perfect harmony between heritage and innovation.",
                            ImageUrl = "blend.jpg",
                            IsActive = true,
                            Name = "Thursday Blend",
                            Price = 7.50m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for product 2",
                            ImageUrl = "2.jpg",
                            IsActive = true,
                            Name = "Product 2",
                            Price = 20.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for product 3",
                            ImageUrl = "3.jpg",
                            IsActive = true,
                            Name = "Product 3",
                            Price = 15.49m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description for product 4",
                            ImageUrl = "4.jpg",
                            IsActive = true,
                            Name = "Product 4",
                            Price = 5.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description for product 5",
                            ImageUrl = "5.jpg",
                            IsActive = true,
                            Name = "Product 5",
                            Price = 8.75m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description for product 6",
                            ImageUrl = "6.jpg",
                            IsActive = false,
                            Name = "Product 6",
                            Price = 12.00m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description for product 7",
                            ImageUrl = "7.jpg",
                            IsActive = true,
                            Name = "Product 7",
                            Price = 30.00m,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("Infrastructure.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
