// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251030082921_AddTotalPriceToOrders")]
    partial class AddTotalPriceToOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Infrastructure.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Infrastructure.Entity.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Infrastructure.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Thursday Blend — Brazil Cascavel × Ethiopia Guji A modern twist on a centuries - old ritual.Thursday Blend brings together the depth and balance of Brazil Cascavel with the vibrant aromatics of Ethiopia Guji,creating a uniquely expressive Turkish coffee experience. Smooth and round with a touch of brightness,it captures the perfect harmony between heritage and innovation.",
                            ImageUrl = "blend.jpg",
                            IsActive = true,
                            Name = "Thursday Blend",
                            Price = 7.50m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Thursday Blend — Brazil Cascavel × Ethiopia Guji A modern twist on a centuries - old ritual.Thursday Blend brings together the depth and balance of Brazil Cascavel with the vibrant aromatics of Ethiopia Guji,creating a uniquely expressive Turkish coffee experience. Smooth and round with a touch of brightness,it captures the perfect harmony between heritage and innovation.",
                            ImageUrl = "blend.jpg",
                            IsActive = true,
                            Name = "Thursday Blend",
                            Price = 7.50m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "Rooted in tradition and built for daily ritual, this cezve is crafted for consistent balance and a timeless silhouette. Its smooth surface and graceful lines reflect the beauty of simplicity — a faithful companion for everyday Turkish coffee brewing. Made from 1 mm solid copper and lined with pure tin, it offers reliable heat distribution and a smooth brewing experience. Lightweight yet enduring, it represents the pure essence of the Turkish coffee craft — elegant, consistent, and built to last. This is more than a coffee pot — it’s a daily expression of heritage, made to bring authentic coffee moments to every home.",
                            ImageUrl = "classic_copper.jpeg",
                            IsActive = true,
                            Name = "Classic Copper Cezve — Traditional Form (1 mm)",
                            Price = 50.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            Description = "Forged with both precision and artistry, this cezve begins with a carefully shaped copper form, then comes to life through hand-hammering and detailed finishing by skilled artisans. Each piece carries its own subtle variations in texture a perfect balance between craftsmanship and consistency. Made from 1.5 mm solid copper and lined with pure tin, it delivers exceptional heat control,durability, and depth of flavor.No two are exactly alike — every cezve bears the signature touch of its maker, blending heritage and refinement in every curve. This is more than a coffee pot — it’s craftsmanship with precision, created to honor both tradition and modernity.",
                            ImageUrl = "heritage.jpeg",
                            IsActive = true,
                            Name = "Heritage Copper Cezve — Hand-Finished (1.5 mm)",
                            Price = 65.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 5,
                            Description = "Trabzon Handcrafted Copper Cezve Forged by hand on the Black Sea coast, this cezve is crafted entirely without molds each one unique in form, balance, and soul. Every curve, every hammer mark reflects the rhythm of its maker, a master coppersmith from Trabzon continuing a tradition that has shaped copper for centuries. Made from 1.5 mm solid copper and lined with pure tin, it offers precise heat control and exceptional durability — designed for the smooth, rich foam of authentic Turkish coffee. No two are ever the same. This is more than a coffee pot — it’s a living piece of craftsmanship, where tradition meets individuality.",
                            ImageUrl = "trabzon.jpeg",
                            IsActive = true,
                            Name = "Trabzon Handcrafted Copper Cezve",
                            Price = 75.00m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 6,
                            Description = "Each piece in this handcrafted copper coffee pot set is forged by skilled artisans, carrying forward the timeless ritual of Turkish coffee with modern elegance. Made from pure copper with a tin lined interior and solid brass handle, this set ensures even heat distribution and long - lasting quality. Perfect for those who value craftsmanship and authenticity in every brew.",
                            ImageUrl = "mix_set.jpeg",
                            IsActive = true,
                            Name = "Handcrafted Copper Coffee Pot Set (3 pcs) Tradition Meets Elegance",
                            Price = 200.00m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 7,
                            Description = "Each piece in this handcrafted copper coffee pot set is forged by skilled artisans, carrying forward the timeless ritual of Turkish coffee with modern elegance. Made from pure copper with a tin lined interior and solid brass handle, this set ensures even heat distribution and long - lasting quality. Perfect for those who value craftsmanship and authenticity in every brew.",
                            ImageUrl = "blendd.png",
                            IsActive = false,
                            Name = "Handcrafted Copper Coffee Pot Set (3 pcs) Tradition Meets Elegance",
                            Price = 200.00m,
                            Stock = 80
                        });
                });

            modelBuilder.Entity("Infrastructure.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Infrastructure.Entity.OrderItem", b =>
                {
                    b.HasOne("Infrastructure.Entity.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Infrastructure.Entity.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
